# Generated by Django 5.2 on 2025-07-23 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("titulaciones", "__first__"),
        ("usrs", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apunte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("pdfdir", models.FileField(upload_to="apuntes/")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("descripcion", models.TextField(default="")),
                ("visualizaciones", models.IntegerField(default=0)),
                ("visible", models.BooleanField(default=False)),
                ("apoyo_docente", models.ManyToManyField(to="usrs.profesor")),
                (
                    "asignatura",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="titulaciones.asignatura",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ejercicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("visualizaciones", models.IntegerField(default=0)),
                ("visible", models.BooleanField(default=False)),
                (
                    "asignatura",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="titulaciones.asignatura",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
