# Generated by Django 5.2 on 2025-07-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0001_initial"),
        ("usrs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="apoyo_docente",
            field=models.ManyToManyField(blank=True, null=True, to="usrs.profesor"),
        ),
    ]
