# Generated by Django 5.2 on 2025-07-21 19:09

import s3_file_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0002_alter_apunte_apoyo_docente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="pdfdir",
            field=s3_file_field.fields.S3FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="apuntes/",
                verbose_name="Archivo PDF",
            ),
        ),
    ]
