# Generated by Django 5.2 on 2025-07-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0003_alter_apunte_pdfdir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="pdfdir",
            field=models.FileField(blank=True, null=True, upload_to="apuntes/"),
        ),
    ]
