# Generated by Django 5.2 on 2025-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0005_alter_apunte_pdfdir"),
        ("usrs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="apoyo_docente",
            field=models.ManyToManyField(to="usrs.profesor"),
        ),
    ]
