"""
Django settings for compartida project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "mozilla_django_oidc",
    "storages",
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django_extensions',

    "apuntes.apps.ApuntesConfig",
    "usrs.apps.UsrsConfig",
    "titulaciones.apps.TitulacionesConfig"
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    
]

# secure
SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

SECURE_HSTS_SECONDS = 300  # 5 minutos
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True  # Solo si vas a inscribirte en preload list

X_FRAME_OPTIONS = 'DENY'

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True


#keyCloack settings
AUTHENTICATION_BACKENDS = [
    'usrs.backends.keycloakOIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
    # ...
]

OIDC_RP_CLIENT_ID = config('KC_CLIENT_ID')
OIDC_RP_CLIENT_SECRET = config('KC_CLIENT_SECRET')

KC_HOST = config('KC_HOST')
KC_REALM = config('KC_REALM')

OIDC_OP_AUTHORIZATION_ENDPOINT = f'http://{KC_HOST}/realms/{KC_REALM}/protocol/openid-connect/auth'
OIDC_OP_TOKEN_ENDPOINT = f'http://{KC_HOST}/realms/{KC_REALM}/protocol/openid-connect/token'
OIDC_OP_USER_ENDPOINT = f'http://{KC_HOST}/realms/{KC_REALM}/protocol/openid-connect/userinfo'
OIDC_OP_JWKS_ENDPOINT = f'http://{KC_HOST}/realms/{KC_REALM}/protocol/openid-connect/certs'
OIDC_OP_LOGOUT_ENDPOINT = f"http://{KC_HOST}/realms/{KC_REALM}/protocol/openid-connect/logout"

OIDC_RP_SCOPES = 'openid profile'


OIDC_RP_SIGN_ALGO = config('KC_ALGO')

LOGIN_REDIRECT_URL = '/usr/login/callback/'
LOGOUT_REDIRECT_URL = '/'

#CAMBIAR EN PRODUCCIÓN
CORS_ALLOWED_ORIGINS = [
    "http://localhost:9000",
]

CORS_ALLOW_CREDENTIALS = True

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


# Minio settings
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": config('MINIO_ACCESS_KEY'),
            "secret_key": config('MINIO_SECRET_KEY'),
            "bucket_name": config('MINIO_BUCKET_NAME'),
            "endpoint_url": config('MINIO_ENDPOINT_URL'),
            "region_name": config('MINIO_REGION', default="us-east-1"),
            "addressing_style": "path",
            "use_ssl": False,
            "verify": False,
            "object_parameters": {
                "ACL": "private",
            },
            # Parámetro para que boto3 genere URLs pre-firmadas con expiración personalizada
            "querystring_auth": True,
            "querystring_expire": 60,  # 1 minuto en segundos
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}



ROOT_URLCONF = "compartida.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "compartida.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "db.sqlite3",
    }
}
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MariaDB usa el backend de MySQL
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),  # o el nombre del servicio si estás en Docker, por ejemplo "mariadb"
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}"""

AUTH_USER_MODEL = 'usrs.UsrDa'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = []


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
