# Generated by Django 5.2 on 2025-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Titulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("codigo", models.CharField(default="", max_length=10, unique=True)),
                ("tipo", models.CharField(blank=True, default="GRA", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        default="",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("creditos", models.IntegerField(default=6)),
                ("curso", models.IntegerField(default=0)),
                ("optativa", models.BooleanField(default=False)),
                ("grados", models.ManyToManyField(to="titulaciones.titulacion")),
            ],
        ),
    ]
