# Generated by Django 5.0.6 on 2025-04-15 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0001_initial"),
        ("usrs", "0002_asignatura_semestre_titulacion_asignaturas_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="pdfdir",
            field=models.FileField(upload_to="uploads/apuntes"),
        ),
        migrations.CreateModel(
            name="ejercicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Enunciado", models.TextField()),
                (
                    "pdfdir",
                    models.FileField(blank=True, upload_to="uploads/ejercicios"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("Visualizaciones", models.IntegerField(default=0)),
                (
                    "asignatura",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usrs.asignatura",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usrs.tema",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
