# Generated by Django 5.0.6 on 2025-04-13 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apuntes", "0001_initial"),
        ("usrs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apunte",
            name="apoyo_docente",
            field=models.ManyToManyField(to="usrs.profesor"),
        ),
        migrations.AddField(
            model_name="apunte",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="apunte",
            name="asignatura",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apuntes.asignatura",
            ),
        ),
    ]
