# Generated by Django 5.0.6 on 2025-04-15 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0002_alter_apunte_pdfdir_ejercicios"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ejercicios",
            old_name="Enunciado",
            new_name="enunciado",
        ),
        migrations.RenameField(
            model_name="ejercicios",
            old_name="Visualizaciones",
            new_name="visualizaciones",
        ),
    ]
