# Generated by Django 5.0.6 on 2025-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="pdfdir",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
