# Generated by Django 5.0.6 on 2025-04-16 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0003_rename_enunciado_ejercicios_enunciado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apunte",
            old_name="descipcion",
            new_name="descripcion",
        ),
    ]
