# Generated by Django 5.0.6 on 2025-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0004_rename_descipcion_apunte_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="apunte",
            name="visualizaciones",
            field=models.IntegerField(default=0),
        ),
    ]
