# Generated by Django 5.0.6 on 2025-04-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0005_apunte_visualizaciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="pdfdir",
            field=models.FileField(upload_to="static/uploads/apuntes"),
        ),
    ]
