# Generated by Django 5.0.6 on 2025-04-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0006_alter_apunte_pdfdir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="pdfdir",
            field=models.FileField(upload_to="media/uploads/apuntes"),
        ),
    ]
