# Generated by Django 5.2 on 2025-04-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0007_alter_apunte_pdfdir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="pdfdir",
            field=models.FileField(upload_to="uploads/apuntes"),
        ),
    ]
