# Generated by Django 5.2 on 2025-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0008_alter_apunte_pdfdir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ejercicios",
            name="pdfdir",
            field=models.FileField(blank=True, upload_to="media/uploads/ejercicios"),
        ),
    ]
