# Generated by Django 5.2 on 2025-04-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0009_alter_ejercicios_pdfdir"),
        ("usrs", "0004_usrda_is_active_usrda_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apunte",
            name="descargas",
        ),
        migrations.AddField(
            model_name="apunte",
            name="tema",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="usrs.tema"
            ),
        ),
        migrations.AlterField(
            model_name="apunte",
            name="pdfdir",
            field=models.FileField(upload_to="media/uploads/apuntes"),
        ),
    ]
