# Generated by Django 5.2 on 2025-04-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0010_remove_apunte_descargas_apunte_tema_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="pdfdir",
            field=models.FileField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="ejercicios",
            name="pdfdir",
            field=models.FileField(blank=True, upload_to="media/"),
        ),
    ]
