# Generated by Django 5.2 on 2025-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0011_alter_apunte_pdfdir_alter_ejercicios_pdfdir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="pdfdir",
            field=models.FileField(upload_to="apuntes/"),
        ),
        migrations.AlterField(
            model_name="ejercicios",
            name="pdfdir",
            field=models.FileField(blank=True, upload_to="ejercicios/"),
        ),
    ]
