# Generated by Django 5.2 on 2025-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0012_alter_apunte_pdfdir_alter_ejercicios_pdfdir"),
    ]

    operations = [
        migrations.AddField(
            model_name="apunte",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ejercicios",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
