# Generated by Django 5.2 on 2025-04-19 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0013_apunte_visible_ejercicios_visible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ejercicios",
            name="pdfdir",
        ),
    ]
