# Generated by Django 5.2 on 2025-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apuntes", "0014_remove_ejercicios_pdfdir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apunte",
            name="visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ejercicios",
            name="visible",
            field=models.BooleanField(default=False),
        ),
    ]
