# Generated by Django 5.2 on 2025-07-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usrs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="titulacion",
            name="tipo",
            field=models.CharField(blank=True, default="GRA", max_length=10),
        ),
    ]
