# Generated by Django 5.0.6 on 2025-04-15 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usrs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignatura",
            name="semestre",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="titulacion",
            name="asignaturas",
            field=models.ManyToManyField(blank=True, to="usrs.asignatura"),
        ),
        migrations.AddField(
            model_name="titulacion",
            name="creditos",
            field=models.IntegerField(default=270),
        ),
        migrations.AlterField(
            model_name="asignatura",
            name="creditos",
            field=models.IntegerField(default=6),
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usrs.asignatura",
                    ),
                ),
            ],
        ),
    ]
