# Generated by Django 5.0.6 on 2025-04-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usrs", "0002_asignatura_semestre_titulacion_asignaturas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usrda",
            name="titulacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usrs.titulacion",
            ),
        ),
    ]
