# Generated by Django 5.0.6 on 2025-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usrs", "0003_alter_usrda_titulacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="usrda",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usrda",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
