# Generated by Django 5.2 on 2025-04-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usrs", "0004_usrda_is_active_usrda_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usrda",
            name="recuento_descargas",
        ),
        migrations.AddField(
            model_name="usrda",
            name="recuento_visualizaciones",
            field=models.IntegerField(default=0),
        ),
    ]
