# Generated by Django 5.2 on 2025-04-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usrs", "0005_remove_usrda_recuento_descargas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesor",
            name="asignaturas",
            field=models.ManyToManyField(blank=True, to="usrs.asignatura"),
        ),
    ]
