# Generated by Django 5.2 on 2025-04-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usrs", "0006_alter_profesor_asignaturas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesor",
            name="asignaturas",
            field=models.ManyToManyField(blank=True, null=True, to="usrs.asignatura"),
        ),
    ]
