# Generated by Django 5.2 on 2025-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usrs", "0007_alter_profesor_asignaturas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesor",
            name="asignaturas",
            field=models.ManyToManyField(blank=True, to="usrs.asignatura"),
        ),
    ]
