# Generated by Django 5.2 on 2025-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usrs", "0008_alter_profesor_asignaturas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usrda",
            name="UPMClassCode",
        ),
        migrations.RemoveField(
            model_name="usrda",
            name="family_name",
        ),
        migrations.AddField(
            model_name="usrda",
            name="codigos_escuela",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="usrda",
            name="tipo_usuario",
            field=models.JSONField(default=list),
        ),
    ]
